color:
  brandColors:
    - '#0B090A'
    - '#CCCFD6'
    - '#A89E83'
    - '#6E6A69'
    - '#414045'
  brandStrength: 1
  lightness: 0.835622
  rhythmicContrast: 0.604407
  saturation: 0.588414
layout_spectrum: 0.376689
name: Balienterprise
typography_spectrum: 0.553209
