color:
  brandColors:
    - '#9CCCE2'
    - '#5A98CB'
    - '#091018'
    - '#405A13'
    - '#7D914C'
  brandStrength: 1
  lightness: 0.835622
  rhythmicContrast: 0.604407
  saturation: 0.588414
layout_spectrum: 0.376689
name: Balienterprise
typography_spectrum: 0.553209
